/** Frozen before thinking evaluation; new development transfer set, not F held-out. */
export const transferGrammarCases = [
  {
    id: 'letter-valid',
    title: '～ながら',
    meaning: '一人同时进行两个动作',
    connection: '动词ます形去ます＋ながら',
    sentence: '手紙を書きながら電話をしました。',
    target: true,
    correct: true,
    min: 85,
  },
  {
    id: 'letter-invalid',
    title: '～ながら',
    meaning: '一人同时进行两个动作',
    connection: '动词ます形去ます＋ながら',
    sentence: '手紙を書くながら電話をしました。',
    target: true,
    correct: false,
    max: 59,
  },
  {
    id: 'understand-valid',
    title: '～やすい',
    meaning: '容易做某事',
    connection: '动词ます形去ます＋やすい',
    sentence: 'この説明は理解しやすいです。',
    target: true,
    correct: true,
    min: 85,
  },
  {
    id: 'understand-invalid',
    title: '～やすい',
    meaning: '容易做某事',
    connection: '动词ます形去ます＋やすい',
    sentence: 'この説明は理解するやすいです。',
    target: true,
    correct: false,
    max: 59,
  },
  {
    id: 'before-valid',
    title: '～前に',
    meaning: '在某动作之前',
    connection: '动词辞书形＋前に',
    sentence: '出発する前に、窓を閉めました。',
    target: true,
    correct: true,
    min: 85,
  },
  {
    id: 'before-invalid',
    title: '～前に',
    meaning: '在某动作之前',
    connection: '动词辞书形＋前に',
    sentence: '出発した前に、窓を閉めました。',
    target: true,
    correct: false,
    max: 59,
  },
  {
    id: 'purpose-valid',
    title: '～ように',
    meaning: '为了使某种状态实现',
    connection: '动词辞书形或ない形＋ように',
    sentence: '遅れないように、早く家を出ました。',
    target: true,
    correct: true,
    min: 85,
  },
  {
    id: 'purpose-alternate',
    title: '～ように',
    meaning: '为了使某种状态实现',
    connection: '动词辞书形或ない形＋ように',
    sentence: '遅れないために、早く家を出ました。',
    target: false,
    correct: false,
    max: 30,
  },
];
export const transferWords = [
  {
    id: 'finish',
    word: '済ませる',
    reading: 'すませる',
    gloss: '把事情做完',
    english: 'finish or complete a task',
    sentence: '宿題を済ませてから、友達と遊びました。',
    furigana:
      '宿題[しゅくだい]を済[す]ませてから、友達[ともだち]と遊[あそ]びました。',
    translation: 'After finishing my homework, I played with my friends.',
    zh: '做完作业后，我和朋友玩了。',
    correct: '宿題を済ませてから、友達と遊びました。',
    wrong: 'バスを済ませて学校に行きました。',
    alternate: '宿題を終えてから、友達と遊びました。',
  },
];
